# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-add_time']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='data_time',
        ),
        migrations.AddField(
            model_name='article',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fdd\u5b58\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='article',
            name='mod_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65e5\u671f'),
        ),
    ]
